### ISSUE TITLE
Why use new $this->model() instead of new $this->model ?

### ISSUE THREAD

**Issue by kkbox2468** [spatie/laravel-searchable#132] opened 2022-04-15 05:26 UTC
### Discussed in https://github.com/spatie/laravel-searchable/discussions/130

<div type='discussions-op-text'>

<sup>Originally posted by **kkbox2468** April 12, 2022</sup>
Hello
I am dissecting some code and came across this,
```
 public function getType(): string
 {
        $model = new $this->model();

        if (property_exists($model, 'searchableType')) {
            return $model->searchableType;
        }

        return $model->getTable();
 }
```
in laravel-searchable/src/ModelSearchAspect.php

As far as I know, instance of ModelSearchAspect  doesn’t have `model` method, so  `__call` function will be executed, but not actually executed.

Actually `new $this->model() ` is equivalent to `new $this->model`, so i don’t know why use `new $this->model()` instead of `new $this->model`.

Did I miss something?
</div>

**Comment by freekmurze** [comment] 2022-04-15 06:17
Duplicate of discussion

**Closed** 2022-04-15 06:17 UTC
